### ISSUE TITLE
assay type conflict

### ISSUE THREAD

**Issue by zagorGit** [NIB-SI/pISA-tree#75]
Missing distinction between wet and dry assay types.
When defining **new** assay **type** (e.g. XX)  **_class dry_**, script states a conflict that the assay type (XX) exits in **_class wet_** (and vice versa). At the same the assay type (XX) is not offered (i.e. visible) to choose when creating dry-lab assay (therefore the need for creation of a new type).

**Comment by ablejec** [comment]
Resolved
