### ISSUE TITLE
Hard coded path 

### ISSUE THREAD

**Issue by carissableker** [NIB-SI/pISA-tree#83]
This probably is planned to be changed or the script (Templates/x.lib/upload.bat) removed before release

https://github.com/NIB-SI/pISA/blob/f20fdd956ab856079bb4e5e70b0d7df10b2412ff/Templates/x.lib/upload.bat#L8

**Comment by ablejec** [comment]
It is meant for local, NIB specific, purpose only. 

Can be removed in the release.
